import { NamedNode, Namespace } from "rdflib";

export const F_NTRIPLES = "application/n-triples";
export const F_NQUADS = "application/n-quads";
export const F_TURTLE = "text/turtle";
export const F_N3 = "text/n3";
export const F_PLAIN = "text/plain";
export const F_JSON = "application/json";
export const F_JSONLD = "application/ld+json";
export const F_RDF_XML = "application/rdf+xml";

export const F_NTRIPLES_DEP = "text/ntriples";
export const F_TURTLE_DEP = "application/x-turtle";

export const NON_CONTENT_EXTS = ["php", "asp", "aspx", "cgi", "jsp"];

// From https://www.w3.org/ns/activitystreams-owl
const as = Namespace("https://www.w3.org/ns/activitystreams#", [
    "actor", "attributedTo", "attachment", "attachments", "author", "bcc", "bto", "cc", "context", "current",
    "first", "generator", "icon", "image", "inReplyTo", "items", "last", "location", "next", "object", "oneOf",
    "anyOf", "prev", "preview", "provider", "replies", "result", "audience", "partOf", "tag", "tags", "target",
    "origin", "instrument", "to", "url", "subject", "relationship", "describes", "formerType", "accuracy",
    "altitude", "content", "name", "downstreamDuplicates", "duration", "endTime", "height", "href", "hreflang",
    "id", "latitude", "longitude", "mediaType", "objectType", "published", "radius", "rating", "rel", "startIndex",
    "startTime", "summary", "totalItems", "units", "updated", "upstreamDuplicates", "verb", "width", "deleted",
    "Accept", "Activity", "Block", "IntransitiveActivity", "Add", "Announce", "Application", "Arrive", "Article",
    "Audio", "Collection", "CollectionPage", "OrderedCollectionPage", "Relationship", "Create", "Delete", "Dislike",
    "Document", "Event", "Flag", "Follow", "Group", "Ignore", "Image", "Invite", "Join", "Leave", "Like", "View",
    "Listen", "Read", "Move", "Travel", "Link", "Mention", "Note", "Object", "Offer", "OrderedCollection",
    "OrderedItems", "Page", "Person", "Organization", "Profile", "Place", "Question", "Reject", "Remove", "Service",
    "TentativeAccept", "TentativeReject", "Tombstone", "Undo", "Update", "Video",
]);

// From http://dublincore.org/specifications/dublin-core/dcmi-terms/2012-06-14/
const dc = Namespace("http://purl.org/dc/terms/", [
    // Properties
    "abstract", "accessRights", "accrualMethod", "accrualPeriodicity", "accrualPolicy", "alternative", "audience",
    "available", "bibliographicCitation", "conformsTo", "contributor", "coverage", "created", "creator", "date",
    "dateAccepted", "dateCopyrighted", "dateSubmitted", "description", "educationLevel", "extent", "format",
    "hasFormat", "hasPart", "hasVersion", "identifier", "instructionalMethod", "isFormatOf", "isPartOf",
    "isReferencedBy", "isReplacedBy", "isRequiredBy", "issued", "isVersionOf", "language", "license", "mediator",
    "medium", "modified", "provenance", "publisher", "references", "relation", "replaces", "requires", "rights",
    "rightsHolder", "source", "spatial", "subject", "tableOfContents", "temporal", "title", "type", "valid",
    // Vocabulary Encoding Schemes
    "DCMIType", "DDC", "IMT", "LCC", "LCSH", "MESH", "NLM", "TGN", "UDC",
    // Classes
    "Agent", "AgentClass", "BibliographicResource", "FileFormat", "Frequency", "Jurisdiction", "LicenseDocument",
    "LinguisticSystem", "Location", "LocationPeriodOrJurisdiction", "MediaType", "MediaTypeOrExtent",
    "MethodOfAccrual", "MethodOfInstruction", "PeriodOfTime", "PhysicalMedium", "PhysicalResource", "Policy",
    "ProvenanceStatement", "RightsStatement", "SizeOrDuration", "Standard",
]);

// From https://www.w3.org/1999/02/22-rdf-syntax-ns#
const rdf = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#", [
    "HTML", "langString", "PlainLiteral", "type", "Property", "Statement", "subject", "predicate", "object",
    "Bag", "Seq", "Alt", "value", "List", "nil", "first", "rest", "XMLLiteral",
]);

// From https://www.w3.org/2000/01/rdf-schema#
const rdfs = Namespace("http://www.w3.org/2000/01/rdf-schema#", [
    "Resource", "Class", "subClassOf", "subPropertyOf", "comment", "label", "domain", "range", "seeAlso",
    "isDefinedBy", "Literal", "Container", "ContainerMembershipProperty", "member", "Datatype",
]);

// From https://schema.org/docs/developers.html#defs
const schema = Namespace("http://schema.org/", [
    "AMRadioChannel", "APIReference", "AboutPage", "AcceptAction", "Accommodation", "AccountingService",
    "AchieveAction", "Action", "ActionAccessSpecification", "ActionStatusType", "ActivateAction", "AddAction",
    "AdministrativeArea", "AdultEntertainment", "AggregateOffer", "AggregateRating", "AgreeAction", "Airline",
    "Airport", "AlignmentObject", "AllocateAction", "AmusementPark", "AnimalShelter", "Answer", "Apartment",
    "ApartmentComplex", "AppendAction", "ApplyAction", "Aquarium", "ArriveAction", "ArtGallery", "Article",
    "AskAction", "AssessAction", "AssignAction", "Attorney", "Audience", "AudioObject", "AuthorizeAction",
    "AutoBodyShop", "AutoDealer", "AutoPartsStore", "AutoRental", "AutoRepair", "AutoWash", "AutomatedTeller",
    "AutomotiveBusiness", "Bakery", "BankAccount", "BankOrCreditUnion", "BarOrPub", "Barcode", "Beach",
    "BeautySalon", "BedAndBreakfast", "BedDetails", "BedType", "BefriendAction", "BikeStore", "Blog", "BlogPosting",
    "BoardingPolicyType", "BodyOfWater", "Book", "BookFormatType", "BookSeries", "BookStore", "BookmarkAction",
    "Boolean", "BorrowAction", "BowlingAlley", "Brand", "BreadcrumbList", "Brewery", "Bridge", "BroadcastChannel",
    "BroadcastEvent", "BroadcastFrequencySpecification", "BroadcastService", "BuddhistTemple", "BusReservation",
    "BusStation", "BusStop", "BusTrip", "BusinessAudience", "BusinessEntityType", "BusinessEvent",
    "BusinessFunction", "BuyAction", "CableOrSatelliteService", "CafeOrCoffeeShop", "Campground", "CampingPitch",
    "Canal", "CancelAction", "Car", "Casino", "CatholicChurch", "Cemetery", "CheckAction", "CheckInAction",
    "CheckOutAction", "CheckoutPage", "ChildCare", "ChildrensEvent", "ChooseAction", "Church", "City", "CityHall",
    "CivicStructure", "ClaimReview", "Clip", "ClothingStore", "Code", "CollectionPage", "CollegeOrUniversity",
    "ComedyClub", "ComedyEvent", "Comment", "CommentAction", "CommunicateAction", "CompoundPriceSpecification",
    "ComputerLanguage", "ComputerStore", "ConfirmAction", "ConsumeAction", "ContactPage", "ContactPoint",
    "ContactPointOption", "Continent", "ControlAction", "ConvenienceStore", "Conversation", "CookAction",
    "Corporation", "Country", "Course", "CourseInstance", "Courthouse", "CreateAction", "CreativeWork",
    "CreativeWorkSeason", "CreativeWorkSeries", "CreditCard", "Crematorium", "CurrencyConversionService",
    "DanceEvent", "DanceGroup", "DataCatalog", "DataDownload", "DataFeed", "DataFeedItem", "DataType", "Dataset",
    "Date", "DateTime", "DatedMoneySpecification", "DayOfWeek", "DaySpa", "DeactivateAction",
    "DefenceEstablishment", "DeleteAction", "DeliveryChargeSpecification", "DeliveryEvent", "DeliveryMethod",
    "Demand", "Dentist", "DepartAction", "DepartmentStore", "DepositAccount", "DigitalDocument",
    "DigitalDocumentPermission", "DigitalDocumentPermissionType", "DisagreeAction", "DiscoverAction",
    "DiscussionForumPosting", "DislikeAction", "Distance", "Distillery", "DonateAction", "DownloadAction",
    "DrawAction", "DrinkAction", "DriveWheelConfigurationValue", "DryCleaningOrLaundry", "Duration", "EatAction",
    "EducationEvent", "EducationalAudience", "EducationalOrganization", "Electrician", "ElectronicsStore",
    "ElementarySchool", "EmailMessage", "Embassy", "EmergencyService", "EmployeeRole", "EmployerAggregateRating",
    "EmploymentAgency", "EndorseAction", "EndorsementRating", "Energy", "EngineSpecification",
    "EntertainmentBusiness", "EntryPoint", "Enumeration", "Episode", "Event", "EventReservation", "EventStatusType",
    "EventVenue", "ExerciseAction", "ExerciseGym", "ExhibitionEvent", "FAQPage", "FMRadioChannel",
    "FastFoodRestaurant", "Festival", "FilmAction", "FinancialProduct", "FinancialService", "FindAction",
    "FireStation", "Flight", "FlightReservation", "Float", "Florist", "FollowAction", "FoodEstablishment",
    "FoodEstablishmentReservation", "FoodEvent", "FoodService", "FurnitureStore", "Game", "GamePlayMode",
    "GameServer", "GameServerStatus", "GardenStore", "GasStation", "GatedResidenceCommunity", "GenderType",
    "GeneralContractor", "GeoCircle", "GeoCoordinates", "GeoShape", "GiveAction", "GolfCourse",
    "GovernmentBuilding", "GovernmentOffice", "GovernmentOrganization", "GovernmentPermit", "GovernmentService",
    "GroceryStore", "HVACBusiness", "HairSalon", "HardwareStore", "HealthAndBeautyBusiness", "HealthClub",
    "HighSchool", "HinduTemple", "HobbyShop", "HomeAndConstructionBusiness", "HomeGoodsStore", "Hospital", "Hostel",
    "Hotel", "HotelRoom", "House", "HousePainter", "HowTo", "HowToDirection", "HowToItem", "HowToSection",
    "HowToStep", "HowToSupply", "HowToTip", "HowToTool", "IceCreamShop", "IgnoreAction", "ImageGallery",
    "ImageObject", "IndividualProduct", "InformAction", "InsertAction", "InstallAction", "InsuranceAgency",
    "Intangible", "Integer", "InteractAction", "InteractionCounter", "InternetCafe", "InvestmentOrDeposit",
    "InviteAction", "Invoice", "ItemAvailability", "ItemList", "ItemListOrderType", "ItemPage", "JewelryStore",
    "JobPosting", "JoinAction", "LakeBodyOfWater", "Landform", "LandmarksOrHistoricalBuildings", "Language",
    "LeaveAction", "LegalService", "LegislativeBuilding", "LendAction", "Library", "LikeAction", "LiquorStore",
    "ListItem", "ListenAction", "LiteraryEvent", "LiveBlogPosting", "LoanOrCredit", "LocalBusiness",
    "LocationFeatureSpecification", "LockerDelivery", "Locksmith", "LodgingBusiness", "LodgingReservation",
    "LoseAction", "Map", "MapCategoryType", "MarryAction", "Mass", "MediaObject", "MediaSubscription",
    "MedicalOrganization", "MeetingRoom", "MensClothingStore", "Menu", "MenuItem", "MenuSection", "Message",
    "MiddleSchool", "MobileApplication", "MobilePhoneStore", "MonetaryAmount", "MonetaryAmountDistribution",
    "Mosque", "Motel", "MotorcycleDealer", "MotorcycleRepair", "Mountain", "MoveAction", "Movie", "MovieClip",
    "MovieRentalStore", "MovieSeries", "MovieTheater", "MovingCompany", "Museum", "MusicAlbum",
    "MusicAlbumProductionType", "MusicAlbumReleaseType", "MusicComposition", "MusicEvent", "MusicGroup",
    "MusicPlaylist", "MusicRecording", "MusicRelease", "MusicReleaseFormatType", "MusicStore", "MusicVenue",
    "MusicVideoObject", "NGO", "NailSalon", "NewsArticle", "NightClub", "Notary", "NoteDigitalDocument", "Number",
    "NutritionInformation", "Occupation", "OceanBodyOfWater", "Offer", "OfferCatalog", "OfferItemCondition",
    "OfficeEquipmentStore", "OnDemandEvent", "OpeningHoursSpecification", "Order", "OrderAction", "OrderItem",
    "OrderStatus", "Organization", "OrganizationRole", "OrganizeAction", "OutletStore", "OwnershipInfo",
    "PaintAction", "Painting", "ParcelDelivery", "ParcelService", "ParentAudience", "Park", "ParkingFacility",
    "PawnShop", "PayAction", "PaymentCard", "PaymentChargeSpecification", "PaymentMethod", "PaymentService",
    "PaymentStatusType", "PeopleAudience", "PerformAction", "PerformanceRole", "PerformingArtsTheater",
    "PerformingGroup", "Periodical", "Permit", "Person", "PetStore", "Pharmacy", "Photograph", "PhotographAction",
    "Physician", "Place", "PlaceOfWorship", "PlanAction", "PlayAction", "Playground", "Plumber", "PoliceStation",
    "Pond", "PostOffice", "PostalAddress", "PreOrderAction", "PrependAction", "Preschool",
    "PresentationDigitalDocument", "PriceSpecification", "Product", "ProductModel", "ProfessionalService",
    "ProfilePage", "ProgramMembership", "PropertyValue", "PropertyValueSpecification", "PublicSwimmingPool",
    "PublicationEvent", "PublicationIssue", "PublicationVolume", "QAPage", "QualitativeValue", "QuantitativeValue",
    "QuantitativeValueDistribution", "Quantity", "Question", "QuoteAction", "RVPark", "RadioChannel", "RadioClip",
    "RadioEpisode", "RadioSeason", "RadioSeries", "RadioStation", "Rating", "ReactAction", "ReadAction",
    "RealEstateAgent", "ReceiveAction", "Recipe", "RecyclingCenter", "RegisterAction", "RejectAction", "RentAction",
    "RentalCarReservation", "ReplaceAction", "ReplyAction", "Report", "Reservation", "ReservationPackage",
    "ReservationStatusType", "ReserveAction", "Reservoir", "Residence", "Resort", "Restaurant", "RestrictedDiet",
    "ResumeAction", "ReturnAction", "Review", "ReviewAction", "RiverBodyOfWater", "Role", "RoofingContractor",
    "Room", "RsvpAction", "RsvpResponseType", "SaleEvent", "ScheduleAction", "ScholarlyArticle", "School",
    "ScreeningEvent", "Sculpture", "SeaBodyOfWater", "SearchAction", "SearchResultsPage", "Season", "Seat",
    "SelfStorage", "SellAction", "SendAction", "Series", "Service", "ServiceChannel", "ShareAction", "ShoeStore",
    "ShoppingCenter", "SingleFamilyResidence", "SiteNavigationElement", "SkiResort", "SocialEvent",
    "SocialMediaPosting", "SoftwareApplication", "SoftwareSourceCode", "SomeProducts", "SpeakableSpecification",
    "Specialty", "SportingGoodsStore", "SportsActivityLocation", "SportsClub", "SportsEvent", "SportsOrganization",
    "SportsTeam", "SpreadsheetDigitalDocument", "StadiumOrArena", "State", "SteeringPositionValue", "Store",
    "StructuredValue", "SubscribeAction", "SubwayStation", "Suite", "SuspendAction", "Synagogue", "TVClip",
    "TVEpisode", "TVSeason", "TVSeries", "Table", "TakeAction", "TattooParlor", "Taxi", "TaxiReservation",
    "TaxiService", "TaxiStand", "TechArticle", "TelevisionChannel", "TelevisionStation", "TennisComplex", "Text",
    "TextDigitalDocument", "TheaterEvent", "TheaterGroup", "Thing", "Ticket", "TieAction", "Time", "TipAction",
    "TireShop", "TouristAttraction", "TouristInformationCenter", "ToyStore", "TrackAction", "TradeAction",
    "TrainReservation", "TrainStation", "TrainTrip", "TransferAction", "TravelAction", "TravelAgency", "Trip",
    "TypeAndQuantityNode", "URL", "UnRegisterAction", "UnitPriceSpecification", "UpdateAction", "UseAction",
    "UserBlocks", "UserCheckins", "UserComments", "UserDownloads", "UserInteraction", "UserLikes", "UserPageVisits",
    "UserPlays", "UserPlusOnes", "UserTweets", "Vehicle", "VideoGallery", "VideoGame", "VideoGameClip",
    "VideoGameSeries", "VideoObject", "ViewAction", "VisualArtsEvent", "VisualArtwork", "Volcano", "VoteAction",
    "WPAdBlock", "WPFooter", "WPHeader", "WPSideBar", "WantAction", "WarrantyPromise", "WarrantyScope",
    "WatchAction", "Waterfall", "WearAction", "WebApplication", "WebPage", "WebPageElement", "WebSite",
    "WholesaleStore", "WinAction", "Winery", "WorkersUnion", "WriteAction", "Zoo", "ActiveActionStatus",
    "AlbumRelease", "AllWheelDriveConfiguration", "AudiobookFormat", "BroadcastRelease", "CDFormat",
    "CassetteFormat", "CoOp", "CommentPermission", "CompilationAlbum", "CompletedActionStatus", "DJMixAlbum",
    "DVDFormat", "DamagedCondition", "DemoAlbum", "DiabeticDiet", "DigitalAudioTapeFormat", "DigitalFormat",
    "Discontinued", "EBook", "EPRelease", "EventCancelled", "EventPostponed", "EventRescheduled", "EventScheduled",
    "FailedActionStatus", "False", "Female", "FourWheelDriveConfiguration", "Friday",
    "FrontWheelDriveConfiguration", "GlutenFreeDiet", "GroupBoardingPolicy", "HalalDiet", "Hardcover",
    "HearingImpairedSupported", "HinduDiet", "InStock", "InStoreOnly", "ItemListOrderAscending",
    "ItemListOrderDescending", "ItemListUnordered", "KosherDiet", "LaserDiscFormat", "LeftHandDriving",
    "LimitedAvailability", "LiveAlbum", "LowCalorieDiet", "LowFatDiet", "LowLactoseDiet", "LowSaltDiet", "Male",
    "MixtapeAlbum", "Monday", "MultiPlayer", "NewCondition", "OfflinePermanently", "OfflineTemporarily",
    "OnSitePickup", "Online", "OnlineFull", "OnlineOnly", "OrderCancelled", "OrderDelivered", "OrderInTransit",
    "OrderPaymentDue", "OrderPickupAvailable", "OrderProblem", "OrderProcessing", "OrderReturned", "OutOfStock",
    "Paperback", "ParkingMap", "PaymentAutomaticallyApplied", "PaymentComplete", "PaymentDeclined", "PaymentDue",
    "PaymentPastDue", "PotentialActionStatus", "PreOrder", "PreSale", "PublicHolidays", "ReadPermission",
    "RearWheelDriveConfiguration", "RefurbishedCondition", "RemixAlbum", "Researcher", "ReservationCancelled",
    "ReservationConfirmed", "ReservationHold", "ReservationPending", "RightHandDriving", "RsvpResponseMaybe",
    "RsvpResponseNo", "RsvpResponseYes", "Saturday", "SeatingMap", "SinglePlayer", "SingleRelease", "SoldOut",
    "SoundtrackAlbum", "SpokenWordAlbum", "StudioAlbum", "Sunday", "Thursday", "TollFree", "TransitMap", "True",
    "Tuesday", "UsedCondition", "VeganDiet", "VegetarianDiet", "VenueMap", "VinylFormat", "Wednesday",
    "WritePermission", "ZoneBoardingPolicy", "acceptedAnswer", "acceptedOffer", "acceptedPaymentMethod",
    "acceptsReservations", "accessCode", "accessMode", "accessModeSufficient", "accessibilityAPI",
    "accessibilityControl", "accessibilityFeature", "accessibilityHazard", "accessibilitySummary", "accountId",
    "accountablePerson", "acquiredFrom", "actionAccessibilityRequirement", "actionPlatform", "actionStatus",
    "actors", "addOn", "additionalName", "additionalNumberOfGuests", "additionalProperty", "additionalType",
    "address", "addressCountry", "addressLocality", "addressRegion", "advanceBookingRequirement", "affiliation",
    "afterMedia", "agent", "aggregateRating", "aircraft", "albumProductionType", "albumReleaseType", "albums",
    "alignmentType", "alternateName", "alternativeHeadline", "amenityFeature", "amount", "amountOfThisGood",
    "annualPercentageRate", "answerCount", "application", "applicationCategory", "applicationSubCategory",
    "applicationSuite", "appliesToDeliveryMethod", "appliesToPaymentMethod", "area", "arrivalAirport",
    "arrivalBusStop", "arrivalGate", "arrivalPlatform", "arrivalStation", "arrivalTerminal", "arrivalTime",
    "artEdition", "artMedium", "artform", "articleBody", "articleSection", "assembly", "assemblyVersion",
    "associatedArticle", "associatedMedia", "athlete", "attendees", "audienceType", "audio", "authenticator",
    "author", "availability", "availabilityEnds", "availabilityStarts", "availableAtOrFrom", "availableChannel",
    "availableDeliveryMethod", "availableFrom", "availableLanguage", "availableThrough", "awards", "awayTeam",
    "baseSalary", "bccRecipient", "bed", "beforeMedia", "benefits", "bestRating", "billingAddress",
    "billingIncrement", "billingPeriod", "birthDate", "birthPlace", "bitrate", "blogPosts", "boardingGroup",
    "boardingPolicy", "bookEdition", "bookFormat", "bookingAgent", "bookingTime", "borrower", "box", "branchCode",
    "branchOf", "brand", "breadcrumb", "broadcastAffiliateOf", "broadcastChannelId", "broadcastDisplayName",
    "broadcastFrequency", "broadcastFrequencyValue", "broadcastOfEvent", "broadcastServiceTier",
    "broadcastTimezone", "broadcaster", "browserRequirements", "busName", "busNumber", "businessFunction", "buyer",
    "byArtist", "calories", "candidate", "caption", "carbohydrateContent", "cargoVolume", "carrier",
    "carrierRequirements", "catalog", "catalogNumber", "category", "ccRecipient", "character", "characterAttribute",
    "characterName", "cheatCode", "checkinTime", "checkoutTime", "childMaxAge", "childMinAge", "children",
    "cholesterolContent", "circle", "citation", "claimReviewed", "clipNumber", "closes", "coach", "codeRepository",
    "colleagues", "collection", "color", "comment", "commentCount", "commentText", "commentTime", "composer",
    "confirmationNumber", "contactOption", "contactPoints", "contactType", "containedIn", "contentRating",
    "contentSize", "contentType", "contentUrl", "contributor", "cookTime", "cookingMethod", "copyrightHolder",
    "copyrightYear", "countriesNotSupported", "countriesSupported", "countryOfOrigin", "course", "courseCode",
    "courseMode", "coursePrerequisites", "coverageEndTime", "coverageStartTime", "creator", "creditedTo",
    "cssSelector", "currenciesAccepted", "currency", "customer", "dataFeedElement", "datasetTimeInterval",
    "dateCreated", "dateDeleted", "dateIssued", "dateModified", "datePosted", "datePublished", "dateRead",
    "dateReceived", "dateSent", "dateVehicleFirstRegistered", "dateline", "dayOfWeek", "deathDate", "deathPlace",
    "defaultValue", "deliveryAddress", "deliveryLeadTime", "deliveryMethod", "deliveryStatus", "department",
    "departureAirport", "departureBusStop", "departureGate", "departurePlatform", "departureStation",
    "departureTerminal", "departureTime", "dependencies", "depth", "device", "directors",
    "disambiguatingDescription", "discount", "discountCode", "discountCurrency", "discusses", "discussionUrl",
    "dissolutionDate", "distance", "distribution", "doorTime", "downloadUrl", "downvoteCount",
    "driveWheelConfiguration", "dropoffLocation", "dropoffTime", "duns", "durationOfWarranty", "duringMedia",
    "editor", "educationalAlignment", "educationalCredentialAwarded", "educationalFramework", "educationalRole",
    "educationalUse", "elevation", "eligibleCustomerType", "eligibleDuration", "eligibleQuantity", "eligibleRegion",
    "eligibleTransactionVolume", "email", "embedUrl", "employees", "employmentType", "encodingType", "encodings",
    "endDate", "endTime", "endorsee", "entertainmentBusiness", "episodeNumber", "episodes", "equal", "error",
    "estimatedCost", "estimatedFlightDuration", "estimatedSalary", "eventStatus", "events", "exifData",
    "expectedArrivalFrom", "expectedArrivalUntil", "expectsAcceptanceOf", "experienceRequirements", "expires",
    "familyName", "fatContent", "faxNumber", "featureList", "feesAndCommissionsSpecification", "fiberContent",
    "fileFormat", "fileSize", "firstPerformance", "flightDistance", "flightNumber", "floorSize", "followee",
    "follows", "foodEstablishment", "foodEvent", "founders", "foundingDate", "foundingLocation", "free",
    "fromLocation", "fuelConsumption", "fuelEfficiency", "fuelType", "funder", "gameItem", "gameLocation",
    "gamePlatform", "gameTip", "gender", "genre", "geo", "geoContains", "geoCoveredBy", "geoCovers", "geoCrosses",
    "geoDisjoint", "geoEquals", "geoIntersects", "geoMidpoint", "geoOverlaps", "geoRadius", "geoTouches",
    "geoWithin", "geographicArea", "givenName", "globalLocationNumber", "grantee", "greater", "greaterOrEqual",
    "gtin12", "gtin13", "gtin14", "gtin8", "hasCourseInstance", "hasDeliveryMethod", "hasDigitalDocumentPermission",
    "hasMenuItem", "hasMenuSection", "hasOccupation", "hasOfferCatalog", "hasPOS", "headline", "height",
    "highPrice", "hiringOrganization", "homeLocation", "homeTeam", "honorificPrefix", "honorificSuffix",
    "hostingOrganization", "hoursAvailable", "httpMethod", "iataCode", "icaoCode", "illustrator", "inAlbum",
    "inBroadcastLineup", "inPlaylist", "incentives", "includedComposition", "includedDataCatalog", "includesObject",
    "industry", "ineligibleRegion", "ingredients", "installUrl", "instructor", "interactionCount",
    "interactionService", "interactionType", "interactivityType", "interestRate", "inventoryLevel",
    "isAccessoryOrSparePartFor", "isBasedOnUrl", "isConsumableFor", "isFamilyFriendly", "isGift", "isLiveBroadcast",
    "isRelatedTo", "isSimilarTo", "isVariantOf", "isbn", "isicV4", "isrcCode", "issn", "issueNumber", "issuedBy",
    "issuedThrough", "iswcCode", "item", "itemCondition", "itemListElement", "itemListOrder", "itemOffered",
    "itemReviewed", "itemShipped", "jobLocation", "jobTitle", "keywords", "knownVehicleDamages", "knows",
    "landlord", "language", "lastReviewed", "latitude", "learningResourceType", "legalName", "leiCode", "lender",
    "lesser", "lesserOrEqual", "license", "line", "liveBlogUpdate", "loanTerm", "locationCreated",
    "lodgingUnitDescription", "lodgingUnitType", "logo", "longitude", "loser", "lowPrice", "lyricist", "lyrics",
    "mainContentOfPage", "manufacturer", "map", "mapType", "maps", "maxPrice", "maxValue",
    "maximumAttendeeCapacity", "mealService", "median", "members", "membershipNumber", "memoryRequirements",
    "mentions", "menu", "menuAddOn", "merchant", "messageAttachment", "mileageFromOdometer", "minPrice", "minValue",
    "minimumPaymentDue", "model", "modifiedTime", "mpn", "multipleValues", "musicArrangement", "musicBy",
    "musicCompositionForm", "musicGroupMember", "musicReleaseFormat", "musicalKey", "naics", "name",
    "namedPosition", "nationality", "netWorth", "nextItem", "nonEqual", "numAdults", "numChildren", "numTracks",
    "numberOfAirbags", "numberOfAxles", "numberOfBeds", "numberOfDoors", "numberOfEmployees", "numberOfEpisodes",
    "numberOfForwardGears", "numberOfItems", "numberOfPages", "numberOfPlayers", "numberOfPreviousOwners",
    "numberOfRooms", "numberOfSeasons", "numberedPosition", "nutrition", "occupancy", "occupationLocation",
    "occupationalCategory", "offerCount", "offers", "openingHours", "openingHoursSpecification", "opens",
    "operatingSystem", "opponent", "option", "orderDate", "orderDelivery", "orderItemNumber", "orderItemStatus",
    "orderNumber", "orderQuantity", "orderStatus", "orderedItem", "organizer", "originAddress", "ownedFrom",
    "ownedThrough", "owns", "pageEnd", "pageStart", "pagination", "parentItem", "parentService", "parents",
    "partOfEpisode", "partOfInvoice", "partOfOrder", "partOfSeason", "partOfTVSeries", "partySize",
    "passengerPriorityStatus", "passengerSequenceNumber", "paymentAccepted", "paymentDue", "paymentMethod",
    "paymentMethodId", "paymentStatus", "paymentUrl", "percentile10", "percentile25", "percentile75",
    "percentile90", "performerIn", "performers", "permissionType", "permissions", "permitAudience",
    "permittedUsage", "petsAllowed", "photos", "pickupLocation", "pickupTime", "playMode", "playerType",
    "playersOnline", "polygon", "postOfficeBoxNumber", "postalCode", "potentialAction", "predecessorOf", "prepTime",
    "previousItem", "previousStartDate", "price", "priceComponent", "priceCurrency", "priceRange",
    "priceSpecification", "priceType", "priceValidUntil", "primaryImageOfPage", "printColumn", "printEdition",
    "printPage", "printSection", "processingTime", "processorRequirements", "producer", "produces", "productID",
    "productSupported", "productionCompany", "productionDate", "proficiencyLevel", "programMembershipUsed",
    "programName", "programmingLanguage", "programmingModel", "propertyID", "proteinContent", "providerMobility",
    "providesService", "publicAccess", "publication", "publishedOn", "publisher", "publishingPrinciples",
    "purchaseDate", "query", "quest", "question", "ratingCount", "ratingValue", "readonlyValue", "realEstateAgent",
    "recipe", "recipeCategory", "recipeCuisine", "recipeInstructions", "recipeYield", "recordLabel",
    "referenceQuantity", "referencesOrder", "regionsAllowed", "relatedLink", "relatedTo", "releaseDate",
    "releaseNotes", "releasedEvent", "relevantOccupation", "remainingAttendeeCapacity", "replacee", "replacer",
    "replyToUrl", "reportNumber", "representativeOfPage", "requiredCollateral", "requiredGender", "requiredMaxAge",
    "requiredMinAge", "requiredQuantity", "requirements", "requiresSubscription", "reservationFor", "reservationId",
    "reservationStatus", "reservedTicket", "responsibilities", "resultComment", "resultReview", "reviewAspect",
    "reviewBody", "reviewCount", "reviewRating", "reviewedBy", "reviews", "rsvpResponse", "runtime",
    "salaryCurrency", "sameAs", "sampleType", "saturatedFatContent", "scheduledPaymentDate", "scheduledTime",
    "schemaVersion", "screenCount", "screenshot", "seasonNumber", "seasons", "seatNumber", "seatRow", "seatSection",
    "seatingType", "securityScreening", "seeks", "sender", "serverStatus", "servesCuisine", "serviceAudience",
    "serviceLocation", "serviceOperator", "servicePhone", "servicePostalAddress", "serviceSmsNumber", "serviceType",
    "serviceUrl", "servingSize", "sharedContent", "siblings", "significantLinks", "skills", "sku", "slogan",
    "smokingAllowed", "sodiumContent", "softwareAddOn", "softwareHelp", "softwareVersion", "sourceOrganization",
    "spatial", "spatialCoverage", "speakable", "specialCommitments", "specialOpeningHoursSpecification",
    "specialty", "sport", "sportsActivityLocation", "sportsEvent", "sportsTeam", "spouse", "starRating",
    "startDate", "startTime", "steeringPosition", "stepValue", "steps", "storageRequirements", "streetAddress",
    "subEvents", "subReservation", "subtitleLanguage", "successorOf", "sugarContent", "suggestedGender",
    "suggestedMaxAge", "suggestedMinAge", "suitableForDiet", "supportingData", "surface", "target",
    "targetDescription", "targetName", "targetPlatform", "targetProduct", "targetUrl", "taxID", "telephone",
    "temporal", "text", "thumbnail", "thumbnailUrl", "tickerSymbol", "ticketNumber", "ticketToken", "ticketedSeat",
    "timeRequired", "title", "toLocation", "toRecipient", "tool", "totalPaymentDue", "totalPrice", "totalTime",
    "touristType", "trackingNumber", "trackingUrl", "tracks", "trailer", "trainName", "trainNumber",
    "transFatContent", "transcript", "translator", "typeOfBed", "typeOfGood", "typicalAgeRange", "underName",
    "unitCode", "unitText", "unsaturatedFatContent", "uploadDate", "upvoteCount", "url", "urlTemplate",
    "userInteractionCount", "validFor", "validFrom", "validIn", "validThrough", "validUntil", "value",
    "valueAddedTaxIncluded", "valueMaxLength", "valueMinLength", "valueName", "valuePattern", "valueReference",
    "valueRequired", "vatID", "vehicleConfiguration", "vehicleEngine", "vehicleIdentificationNumber",
    "vehicleInteriorColor", "vehicleInteriorType", "vehicleModelDate", "vehicleSeatingCapacity",
    "vehicleTransmission", "vendor", "version", "video", "videoFormat", "videoFrameSize", "videoQuality",
    "volumeNumber", "warrantyPromise", "warrantyScope", "webCheckinTime", "weight", "width", "winner", "wordCount",
    "workHours", "workLocation", "workPerformed", "workPresented", "worksFor", "worstRating", "xpath",
    "yearlyRevenue", "yearsInOperation", "actionApplication", "actionOption", "actor", "album", "albumRelease",
    "alumni", "alumniOf", "artworkSurface", "attendee", "audience", "availableOnDevice", "award", "blogPost",
    "broker", "codeSampleType", "colleague", "contactPoint", "containsPlace", "containsSeason", "contentLocation",
    "dataset", "description", "director", "duration", "employee", "encodesCreativeWork", "encodingFormat",
    "episode", "event", "exampleOfWork", "executableLibraryName", "exerciseCourse", "founder", "game", "gameServer",
    "hasBroadcastChannel", "hasMenu", "inLanguage", "incentiveCompensation", "interactionStatistic",
    "isAccessibleForFree", "isBasedOn", "jobBenefits", "mainEntity", "mainEntityOfPage", "makesOffer", "offeredBy",
    "parent", "partOfSeries", "paymentDueDate", "performTime", "performer", "photo", "provider",
    "providesBroadcastService", "recipeIngredient", "recordedAs", "recordedAt", "recordedIn", "recordingOf",
    "releaseOf", "review", "roleName", "runtimePlatform", "season", "serialNumber", "serviceArea", "serviceOutput",
    "sibling", "significantLink", "softwareRequirements", "sponsor", "subOrganization", "subjectOf",
    "suggestedAnswer", "superEvent", "targetCollection", "temporalCoverage", "track", "warranty", "workExample",
    "yield", "about", "competitor", "containedInPlace", "encoding", "hasMap", "image", "material", "memberOf",
    "parentOrganization", "result", "seller", "step", "subEvent", "supply", "workFeatured", "areaServed",
    "includedInDataCatalog", "member", "recipient", "hasPart", "isPartOf", "position", "instrument", "object",
    "location", "participant", "identifier",
]);

// From https://www.w3.org/ns/shacl.ttl
const sh = Namespace("http://www.w3.org/ns/shacl#", [
    "Shape", "NodeShape", "PropertyShape", "deactivated", "targetClass", "targetNode", "targetObjectsOf",
    "targetSubjectsOf", "message", "severity", "NodeKind", "BlankNode", "BlankNodeOrIRI", "BlankNodeOrLiteral",
    "IRI", "IRIOrLiteral", "Literal", "ValidationReport", "conforms", "result", "shapesGraphWellFormed",
    "AbstractResult", "ValidationResult", "Severity", "Info", "Violation", "Warning", "detail", "focusNode",
    "resultMessage", "resultPath", "resultSeverity", "sourceConstraint", "sourceShape", "sourceConstraintComponent",
    "value", "shapesGraph", "suggestedShapesGraph", "entailment", "path", "inversePath", "alternativePath",
    "zeroOrMorePath", "oneOrMorePath", "zeroOrOnePath", "Parameterizable", "parameter", "labelTemplate",
    "Parameter", "optional", "ConstraintComponent", "validator", "nodeValidator", "propertyValidator", "Validator",
    "SPARQLAskValidator", "SPARQLSelectValidator", "AndConstraintComponent", "AndConstraintComponent-and", "and",
    "ClassConstraintComponent", "ClassConstraintComponent-class", "class", "ClosedConstraintComponent",
    "ClosedConstraintComponent-closed", "ClosedConstraintComponent-ignoredProperties", "closed",
    "ignoredProperties", "DatatypeConstraintComponent", "DatatypeConstraintComponent-datatype", "datatype",
    "DisjointConstraintComponent", "DisjointConstraintComponent-disjoint", "disjoint", "EqualsConstraintComponent",
    "EqualsConstraintComponent-equals", "equals", "HasValueConstraintComponent",
    "HasValueConstraintComponent-hasValue", "hasValue", "InConstraintComponent", "InConstraintComponent-in", "in",
    "LanguageInConstraintComponent", "LanguageInConstraintComponent-languageIn", "languageIn",
    "LessThanConstraintComponent", "LessThanConstraintComponent-lessThan", "lessThan",
    "LessThanOrEqualsConstraintComponent", "LessThanOrEqualsConstraintComponent-lessThanOrEquals",
    "lessThanOrEquals", "MaxCountConstraintComponent", "MaxCountConstraintComponent-maxCount", "maxCount",
    "MaxExclusiveConstraintComponent", "MaxExclusiveConstraintComponent-maxExclusive", "maxExclusive",
    "MaxInclusiveConstraintComponent", "MaxInclusiveConstraintComponent-maxInclusive", "maxInclusive",
    "MaxLengthConstraintComponent", "MaxLengthConstraintComponent-maxLength", "maxLength",
    "MinCountConstraintComponent", "MinCountConstraintComponent-minCount", "minCount",
    "MinExclusiveConstraintComponent", "MinExclusiveConstraintComponent-minExclusive", "minExclusive",
    "MinInclusiveConstraintComponent", "MinInclusiveConstraintComponent-minInclusive", "minInclusive",
    "MinLengthConstraintComponent", "MinLengthConstraintComponent-minLength", "minLength",
    "NodeConstraintComponent", "NodeConstraintComponent-node", "node", "NodeKindConstraintComponent",
    "NodeKindConstraintComponent-nodeKind", "nodeKind", "NotConstraintComponent", "NotConstraintComponent-not",
    "not", "OrConstraintComponent", "OrConstraintComponent-or", "or", "PatternConstraintComponent",
    "PatternConstraintComponent-pattern", "PatternConstraintComponent-flags", "flags", "pattern",
    "PropertyConstraintComponent", "PropertyConstraintComponent-property", "property",
    "QualifiedMaxCountConstraintComponent", "QualifiedMaxCountConstraintComponent-qualifiedMaxCount",
    "QualifiedMaxCountConstraintComponent-qualifiedValueShape",
    "QualifiedMaxCountConstraintComponent-qualifiedValueShapesDisjoint", "QualifiedMinCountConstraintComponent",
    "QualifiedMinCountConstraintComponent-qualifiedMinCount",
    "QualifiedMinCountConstraintComponent-qualifiedValueShape",
    "QualifiedMinCountConstraintComponent-qualifiedValueShapesDisjoint", "qualifiedMaxCount", "qualifiedMinCount",
    "qualifiedValueShape", "qualifiedValueShapesDisjoint", "UniqueLangConstraintComponent",
    "UniqueLangConstraintComponent-uniqueLang", "uniqueLang", "XoneConstraintComponent",
    "XoneConstraintComponent-xone", "xone", "SPARQLExecutable", "SPARQLAskExecutable", "ask",
    "SPARQLConstructExecutable", "construct", "SPARQLSelectExecutable", "select", "SPARQLUpdateExecutable",
    "update", "prefixes", "PrefixDeclaration", "declare", "prefix", "namespace", "SPARQLConstraintComponent",
    "SPARQLConstraintComponent-sparql", "sparql", "SPARQLConstraint", "defaultValue", "description", "group",
    "name", "order", "PropertyGroup", "target", "Target", "TargetType", "SPARQLTarget", "SPARQLTargetType",
    "Function", "returnType", "SPARQLFunction", "resultAnnotation", "ResultAnnotation", "annotationProperty",
    "annotationValue", "annotationVarName", "this", "filterShape", "nodes", "intersection", "union",
    "ExpressionConstraintComponent", "ExpressionConstraintComponent-expression", "expression", "Rule", "rule",
    "condition", "TripleRule", "subject", "predicate", "object", "SPARQLRule", "JSExecutable", "JSTarget",
    "JSTargetType", "JSConstraint", "JSConstraintComponent", "JSConstraint-js", "js", "jsFunctionName", "jsLibrary",
    "jsLibraryURL", "JSFunction", "JSLibrary", "JSRule", "JSValidator",
]);

// From https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/#sec-datatypes-and-facets with subtractions from
// https://www.w3.org/2011/rdf-wg/wiki/XSD_Datatypes which don't match any mapping
const xsd = Namespace("http://www.w3.org/2001/XMLSchema#", [
    "string", "boolean", "float", "double", "decimal", "dateTime", "time", "date", "gYearMonth", "gYear",
    "gMonthDay", "gDay", "gMonth", "hexBinary", "base64Binary", "anyURI", "normalizedString", "token", "language",
    "NMTOKEN", "Name", "NCName", "integer", "nonPositiveInteger", "negativeInteger", "long", "int", "short", "byte",
    "nonNegativeInteger", "unsignedLong", "unsignedInt", "unsignedShort", "unsignedByte", "positiveInteger",
    "yearMonthDuration", "dayTimeDuration", "dateTimeStamp",
]);

export const defaultNS = Object.freeze({
    argu: Namespace("https://argu.co/ns/core#"),
    as,
    bibo: Namespace("http://purl.org/ontology/bibo/"),
    cc: Namespace("http://creativecommons.org/ns#"),
    dbo: Namespace("http://dbpedia.org/ontology/"),
    dbp: Namespace("http://dbpedia.org/property/"),
    dbpedia: Namespace("http://dbpedia.org/resource/"),
    dc,
    dcat: Namespace("http://www.w3.org/ns/dcat#"),
    dctype: Namespace("http://purl.org/dc/dcmitype/"),
    ex: Namespace("http://example.com/ns#"),
    example: Namespace("http://www.example.com/"),
    fhir: Namespace("http://hl7.org/fhir/"),
    fhir3: Namespace("http://hl7.org/fhir/STU3"),
    foaf: Namespace("http://xmlns.com/foaf/0.1/"),
    geo: Namespace("http://www.w3.org/2003/01/geo/wgs84_pos#"),
    http: Namespace("http://www.w3.org/2011/http#"),
    http07: Namespace("http://www.w3.org/2007/ont/http#"),
    httph: Namespace("http://www.w3.org/2007/ont/httph#"),
    hydra: Namespace("http://www.w3.org/ns/hydra/core#"),
    ianalr: Namespace("http://www.iana.org/assignments/link-relations/"),
    link: Namespace("http://www.w3.org/2007/ont/link#"),
    ll: Namespace("http://purl.org/link-lib/"),
    owl: Namespace("http://www.w3.org/2002/07/owl#"),
    p: Namespace("http://www.wikidata.org/prop/"),
    prov: Namespace("http://www.w3.org/ns/prov#"),
    qb: Namespace("http://purl.org/linked-data/cube#"),
    rdf,
    rdfs,
    schema,
    sh,
    skos: Namespace("http://www.w3.org/2004/02/skos/core#"),
    wd: Namespace("http://www.wikidata.org/entity/"),
    wdata: Namespace("https://www.wikidata.org/wiki/Special:EntityData/"),
    wdref: Namespace("http://www.wikidata.org/reference/"),
    wds: Namespace("http://www.wikidata.org/entity/statement/"),
    wdt: Namespace("http://www.wikidata.org/prop/direct/"),
    wdv: Namespace("http://www.wikidata.org/value/"),
    xmlns: Namespace("http://www.w3.org/2000/xmlns/"),
    xsd,
});

export const DEFAULT_TOPOLOGY: NamedNode = defaultNS.ll("defaultTopology");

/** Constant used to determine that a class is used to render a type rather than a property. */
export const RENDER_CLASS_NAME: NamedNode = defaultNS.ll("typeRenderClass");

export const MAIN_NODE_DEFAULT_IRI = defaultNS.ll("targetResource");
// tslint:disable-next-line ban-types
export const NON_DATA_OBJECTS_CTORS: Function[] = [
    Array,
    ArrayBuffer,
    Boolean,
    DataView,
    Date,
    Error,
    EvalError,
    Float32Array,
    Float64Array,
    Int16Array,
    Int32Array,
    Int8Array,
    Intl.Collator,
    Intl.DateTimeFormat,
    Intl.NumberFormat,
    Map,
    Number,
    Promise,
    (typeof Proxy !== "undefined" ? Proxy : undefined)!,
    RangeError,
    ReferenceError,
    RegExp,
    Set,
].filter(Boolean);
export const MSG_BAD_REQUEST = "Request failed with bad status code";
export const MSG_INCORRECT_TARGET = "Collections or Literals can't be the target";
export const MSG_URL_UNDEFINED = "No url given with action.";
export const MSG_URL_UNRESOLVABLE = "Can't execute action with non-named-node url.";
export const MSG_OBJECT_NOT_IRI = "Action object property must be an IRI.";
